---
bibliography: [bibliography.bib]
site: bookdown::bookdown_site
---

```{r setup, include=FALSE}
options(digits = 4)

# Install the packages needed by this book
lapply(c("ggplot2", "readr", "dplyr", "tidyr", "forcats", "tibble","kableExtra", "psych", "knitr"), function(pkg) {
  if(system.file(package = pkg) == "") install.packages(pkg)
})

# Import libraries
library(knitr)
library(readr)
library(dplyr)
library(tidyr)
library(tibble)
library(forcats)
library(kableExtra)
library(psych)
library(ggplot2)

Sys.setlocale("LC_ALL","English")

row_group_label_fonts <- list(
list(bold = TRUE, italic = TRUE),
list(bold = FALSE, italic = FALSE)
)

```



```{r dataLoadResults, echo=FALSE, warning=FALSE}

Compare_novel_dat <- read_rds(file = "../src/cases/Compare_novel_dat.rds")
LIST_novel_tbl <- read_rds(file = "../src/cases/LIST_novel_tbl.rds")
STEC_novel_tbl <- read_rds(file = "../src/cases/STEC_novel_tbl.rds")
SHIG_novel_tbl <- read_rds(file = "../src/cases/SHIG_novel_tbl.rds")
SALM_novel_tbl <- read_rds(file = "../src/cases/SALM_novel_tbl.rds")

Compare_stateOfTheArt_LIST_dat <- read_rds(file = "../src/cases/Compare_stateOfTheArt_LIST_dat.rds")
Compare_stateOfTheArt_SHIG_dat <- read_rds(file = "../src/cases/Compare_stateOfTheArt_SHIG_dat.rds")
Compare_stateOfTheArt_STEC_dat <- read_rds(file = "../src/cases/Compare_stateOfTheArt_STEC_dat.rds")
Compare_stateOfTheArt_SALM_dat <- read_rds(file = "../src/cases/Compare_stateOfTheArt_SALM_dat.rds")

LIST_LogS <- LIST_novel_tbl %>%
  group_by(method) %>%
  distinct(avgLogS)

STEC_LogS <- STEC_novel_tbl %>%
  group_by(method) %>%
  distinct(avgLogS)

SHIG_LogS <- SHIG_novel_tbl %>%
  group_by(method) %>%
  distinct(avgLogS)

SALM_LogS <- SALM_novel_tbl %>%
  group_by(method) %>%
  distinct(avgLogS)

LIST_alarms_StateOfTheArt <- Compare_stateOfTheArt_LIST_dat %>% filter(Date %in% dateOfAlarm)
SHIG_alarms_StateOfTheArt <- Compare_stateOfTheArt_SHIG_dat %>% filter(Date %in% dateOfAlarm)
STEC_alarms_StateOfTheArt <- Compare_stateOfTheArt_STEC_dat %>% filter(Date %in% dateOfAlarm)
SALM_alarms_StateOfTheArt <- Compare_stateOfTheArt_SALM_dat %>% filter(Date %in% dateOfAlarm)


LIST_alarms_Farrington <- LIST_alarms_StateOfTheArt %>% filter(method == "Farrington") 
STEC_alarms_Farrington <- STEC_alarms_StateOfTheArt %>% filter(method == "Farrington") 
SHIG_alarms_Farrington <- SHIG_alarms_StateOfTheArt %>% filter(method == "Farrington") 
SALM_alarms_Farrington <- SALM_alarms_StateOfTheArt %>% filter(method == "Farrington") 

LIST_alarms_Farrington %>% summarize(nAlarm = sum(alarm)) %>% .$nAlarm

LIST_alarms_Noufaily <- LIST_alarms_StateOfTheArt %>% filter(method == "Noufaily") 
STEC_alarms_Noufaily <- STEC_alarms_StateOfTheArt %>% filter(method == "Noufaily") 
SHIG_alarms_Noufaily <- SHIG_alarms_StateOfTheArt %>% filter(method == "Noufaily") 
SALM_alarms_Noufaily <- SALM_alarms_StateOfTheArt %>% filter(method == "Noufaily") 

LIST_alarms <- Compare_novel_dat %>% filter(alarm) %>% summarize(alarms=unique(Date))

```